-- Seat Reservation — database schema (PostgreSQL 16)
-- This file is the canonical schema reference. The Drizzle schema in
-- src/lib/db/schema.ts mirrors it; migrations are generated from there.
-- Constraints worth highlighting:
--   * Partial unique index on reservations enforces "at most one active
--     reservation per seat" at the database layer.
--   * sessions.id stores sha256(token), never the raw token.
--   * payments.idempotency_key and webhook_events.(provider,event_id) are
--     the two idempotency surfaces.

-- Enable case-insensitive text for emails and gen_random_uuid().
CREATE EXTENSION IF NOT EXISTS citext;
CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- ─── users ────────────────────────────────────────────────────────────
CREATE TABLE users (
  id            uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  email         citext NOT NULL UNIQUE,
  password_hash text   NOT NULL,
  created_at    timestamptz NOT NULL DEFAULT now()
);

-- ─── sessions ─────────────────────────────────────────────────────────
-- The cookie carries the raw token. We store sha256(token) so a DB-only
-- breach (no app secret leak) does not yield session takeover.
-- expires_at  = absolute 90-day cap from creation
-- last_used_at = sliding 90-day inactivity window
-- A session is valid iff now < expires_at AND now - last_used_at < 90d.
CREATE TABLE sessions (
  id           text PRIMARY KEY,                 -- sha256(token) hex
  user_id      uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  expires_at   timestamptz NOT NULL,
  last_used_at timestamptz NOT NULL DEFAULT now(),
  created_at   timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX sessions_user_id_idx    ON sessions (user_id);
CREATE INDEX sessions_expires_at_idx ON sessions (expires_at);

-- ─── seats ────────────────────────────────────────────────────────────
CREATE TABLE seats (
  id          uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  label       text NOT NULL UNIQUE,              -- "A1", "A2", "A3"
  price_cents integer NOT NULL CHECK (price_cents > 0),
  currency    text NOT NULL CHECK (length(currency) = 3),
  created_at  timestamptz NOT NULL DEFAULT now()
);

-- ─── reservations ─────────────────────────────────────────────────────
-- Explicit FSM via an enum: illegal states are unrepresentable.
CREATE TYPE reservation_status AS ENUM (
  'held',       -- user selected, hold_expires_at in the future
  'paying',     -- user clicked Pay, payment intent created with provider
  'confirmed',  -- payment succeeded, terminal
  'expired',    -- hold TTL elapsed without payment, terminal
  'cancelled',  -- user cancelled before paying, terminal
  'failed'      -- payment failed, terminal
);

CREATE TABLE reservations (
  id              uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  seat_id         uuid NOT NULL REFERENCES seats(id),
  user_id         uuid NOT NULL REFERENCES users(id),
  status          reservation_status NOT NULL,
  hold_expires_at timestamptz,                   -- only meaningful when status IN ('held','paying')
  created_at      timestamptz NOT NULL DEFAULT now(),
  updated_at      timestamptz NOT NULL DEFAULT now()
);

-- ╔══════════════════════════════════════════════════════════════════════╗
-- ║ THE invariant: at most one active reservation per seat, enforced by  ║
-- ║ the database regardless of application bugs. This is the load-       ║
-- ║ bearing constraint of the whole system.                              ║
-- ╚══════════════════════════════════════════════════════════════════════╝
CREATE UNIQUE INDEX one_active_reservation_per_seat
  ON reservations (seat_id)
  WHERE status IN ('held', 'paying', 'confirmed');

CREATE INDEX reservations_user_id_idx ON reservations (user_id);
CREATE INDEX reservations_hold_expiry_idx
  ON reservations (hold_expires_at)
  WHERE status IN ('held', 'paying');

-- ─── payments ─────────────────────────────────────────────────────────
CREATE TYPE payment_status AS ENUM ('pending', 'succeeded', 'failed', 'cancelled');

CREATE TABLE payments (
  id                 uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  reservation_id     uuid NOT NULL UNIQUE REFERENCES reservations(id),
  provider           text NOT NULL,                  -- 'mock' for us; 'stripe' later
  provider_intent_id text NOT NULL UNIQUE,
  status             payment_status NOT NULL DEFAULT 'pending',
  amount_cents       integer NOT NULL CHECK (amount_cents > 0),
  currency           text    NOT NULL CHECK (length(currency) = 3),
  idempotency_key    text NOT NULL UNIQUE,           -- generated by app when calling provider
  created_at         timestamptz NOT NULL DEFAULT now(),
  updated_at         timestamptz NOT NULL DEFAULT now()
);

-- ─── webhook_events ───────────────────────────────────────────────────
-- Inbound webhook idempotency. A re-delivered event is a no-op:
-- first INSERT wins, subsequent attempts hit the UNIQUE and we return 200.
CREATE TABLE webhook_events (
  id           uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  provider     text NOT NULL,
  event_id     text NOT NULL,
  payload      jsonb NOT NULL,
  received_at  timestamptz NOT NULL DEFAULT now(),
  processed_at timestamptz,
  UNIQUE (provider, event_id)
);

-- ─── audit_log ────────────────────────────────────────────────────────
-- Minimal audit trail for unusual events: failed transitions, signature
-- failures, manual recoveries. Deliberately a single table for this scope.
CREATE TABLE audit_log (
  id          uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  at          timestamptz NOT NULL DEFAULT now(),
  actor       text,                                  -- user_id::text, 'system', or 'webhook'
  action      text NOT NULL,
  target_kind text,
  target_id   uuid,
  detail      jsonb
);
CREATE INDEX audit_log_target_idx ON audit_log (target_kind, target_id);
CREATE INDEX audit_log_at_idx     ON audit_log (at DESC);
